version: "3.8"
services:
    frontend:
        image: mehtasankets/mmflow-frontend:$VERSION
        ports:
            - "8080:8080"
    backend:
        image: mehtasankets/mmflow-backend:$VERSION
        environment: 
            - MMFLOW_DB_PATH=/mmflow.db
            - CLIENT_ID
        ports:
            - "8090:8090"
        volumes:
            - ${MMFLOW_DB_HOST_LOCATION}:/mmflow.db
