version: "3.8"
services:
    frontend:
        build: ./frontend
        ports:
            - "8080:8080"
    backend:
        build: ./backend
        environment: 
            - MMFLOW_DB_PATH=/mmflow.db
            - CLIENT_ID
        ports:
            - "8090:8090"
        volumes:
            - ${MMFLOW_DB_HOST_LOCATION}:/mmflow.db